name: TEST slack-notify-publish

on:
  workflow_dispatch: {}

jobs:
  test:
    uses: janis-commerce/.github/.github/workflows/slack-notify-publish.yml@master
    with:
      username: Log (test)
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
